### ISSUE TITLE
OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by HotsHom** [yetanalytics/lrsql#230] opened 2022-06-04 20:07 UTC
Hello, I ran into a problem. There is a server with 4GB of RAM. I want to check LRS on https://lrstest.adlnet.gov /, however, after a small number of requests, the Java heap space error appears. Can you help, what could be the problem
[log.txt](https://github.com/yetanalytics/lrsql/files/8838622/log.txt)

**Comment by kelvinqian00** [comment] 2022-06-06 13:44
Hello @HotsHom!

I attempted to reproduce your error on a Docker image that used only 2 GB of RAM, using the LRS conformance test suite, yet we did not get any error. Can you please tell us the following information?
- Your Java heap size (most important)
- The version of SQL LRS you are using
- The log file of the LRS conformance test suite (_not_ SQL LRS itself) (you can create a log file by [running the test suite in the CLI](https://github.com/adlnet/lrs-conformance-test-suite#running-the-test-suite) and then finding it in the `log` directory)

**Comment by kelvinqian00** [comment] 2022-06-06 18:44
I've looked into this with your given info and I am still unable to reproduce your error, even with manually setting `-Xms64m -Xmx256m` (which correspond to the initial and max heap sizes you listed, respectively). As such I have a few more questions:
- Does the OOM error go away if you increase the maximum heap size?
- Does this error occur if you run SQL LRS on any machines _besides_ your server? If not, that may indicate that the issue stems from a particular configuration of that server.
- Are you using Docker or downloading SQL LRS directly?
- Just to clarify, are the underscores and asterisks in the URLs in your configuration just for obfuscation and not part of the _actual_ URLs you're using?

**Comment by HotsHom** [comment] 2022-07-30 20:38
I apologize for the late response. I tried to run on another system (still Window), attached java parameters. The error is still the same when performing tests on lrstest.adlnet.gov . 
There may be a problem, of course, in the size of the heap, but I can no longer imagine where else it can be changed. I tried using Windows environment variables, tried adding parameters to the file bin/run_sqlite.sh

**Comment by kelvinqian00** [comment] 2022-08-02 18:08
So it appears that you are running SQL LRS on Windows, is that correct? Given that SQL LRS on Windows has a unique startup procedure*, can you describe the steps you went through to start SQL LRS?

\* Most notably you need to run the Windows executable and not the shell file, so I am not sure why you were adding parameters to `bin/run_sqlite.sh`.

**Comment by HotsHom** [comment] 2022-08-02 23:08
I download the latest version of the release from git
Unpack
it and run it sqlrs.exe

The problem was not reproduced on the Linux system, everything went smoothly there and everything works

**Comment by kelvinqian00** [comment] 2022-08-04 18:21
So we were finally able to reproduce the OOM error on Windows, indicating that it's a problem specific to that platform. We are still not sure why this is the case, but we will continue looking into it.

**Comment by kelvinqian00** [comment] 2022-12-08 22:19
Hello @HotsHom,

Apologies for the very long wait, but we are currently working on addressing this bug, which we have also now encountered on certain Linux systems. It appears that this bug relates to encoding - in environments where the default charset is not set to UTF-8, Unicode strings will be improperly encoded/decoded, which will not only cause OOM errors, but also (if we increase the memory cap) cause the conformance tests to fail anyways.

We currently have a PR aimed at addressing this: https://github.com/yetanalytics/lrsql/pull/260

**Comment by kelvinqian00** [comment] 2022-12-13 18:28
Our fix has been applied to version [v0.4.0](https://github.com/yetanalytics/lrsql/releases/tag/v0.4.0).

**Closed by kelvinqian00** 2022-12-13 18:28 UTC
